### PR TITLE
Free methods of class_copyMethodList

### PR DESCRIPTION
**Pull request by zhongwuzw**

### CODE REVIEW

**Comment by zhongwuzw** [comment]
Are there any cases which would lead to disorder of lazy initialization in `WCTBinding`?

```
    for (NSString *selName in [synthesizations sortedArrayUsingSelector:@selector(compare:)]) {
        SEL selector = NSSelectorFromString(selName);
        IMP imp = [m_cls methodForSelector:selector];
        ((void (*)(Class, SEL, WCTBinding &)) imp)(m_cls, selector, *this);
    }
```

**Comment by RingoD** [comment]
I think no.
We use `__COUNTER__` macro which generated by compiler to order the ORM methods. It will be auto increment with the order of implementation.

**Comment by zhongwuzw** [comment]
@RingoD ,so what's the reason here to sort the array? The commit log said `Crash fixed for unordered call`, so the methods list may not consistent with the order of declare?

```
[synthesizations sortedArrayUsingSelector:@selector(compare:)]
```

**Comment by RingoD** [comment]
`class_copyMethodList` does not return an ordered list in all time.

**Comment by zhongwuzw** [comment]
@RingoD 🤔 , interesting, `class_copyMethodList` just copy `cls->data()->methods` of `cls`, so compiler does the reorder things.

But sorted `synthesizations` did not work well, the `__COUNTER__` macro increase progressively, but it's not consistent with the declaration.  You can try `ORMColumnCoding` testcase, the caller order of  `binding                                                            .addColumnBinding<__WCDB_PROPERTY_TYPE(className, propertyName)>( WCDB_STRINGIFY(propertyName), columnName);`  is not consistent with declaration of `propertyName`.

I tried on simulator `iPhone8` `11.3`.

And sort in here is necessary? It's unrelated each other IMO. 😂

**Comment by RingoD** [comment]
It's the output of `others` variable before sorting.
Obviously, it's not sorted.

```
<__NSArrayM 0x600000055db0>(
__wcdb_ORMColumnCoding_default_7:,
__wcdb_ORMColumnCoding_default_11:,
__wcdb_ORMColumnCoding_default_1:,
__wcdb_ORMColumnCoding_default_3:,
__wcdb_ORMColumnCoding_default_5:,
__wcdb_ORMColumnCoding_default_9:,
__wcdb_ORMColumnCoding_default_13:,
__wcdb_ORMColumnCoding_default_15:,
__wcdb_ORMColumnCoding_default_17:,
__wcdb_ORMColumnCoding_default_19:,
__wcdb_ORMColumnCoding_default_21:
)
```

**Comment by zhongwuzw** [comment]
@RingoD Emm, you maybe misunderstand my thoughts, for example below, it's the `ORMColumnCoding` declarations, after the sorted of `synthesizations`, although the `__wcdb_ORMColumnCoding_synthesize_*` is ascending, but the the call of the `binding .addColumnBinding<__WCDB_PROPERTY_TYPE(className, propertyName)>( WCDB_STRINGIFY(propertyName), columnName);` is not consistent with the order of `WCDB_SYNTHESIZE_DEFAULT`, which means, maybe `WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, dateValue, nil)` call before `WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, int32Value, 0)`. So the order of `syntheszations` are not work.

```
@implementation ORMColumnCoding

WCDB_IMPLEMENTATION(ORMColumnCoding)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, int32Value, 0)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, int64Value, 0)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, uint32Value, 0)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, uint64Value, 0)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, floatValue, 0)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, doubleValue, 0)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, stringValue, nil)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, numberValue, nil)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, dateValue, nil)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, dataValue, nil)
WCDB_SYNTHESIZE_DEFAULT(ORMColumnCoding, arrayValue, nil)
```

**Comment by RingoD** [comment]
So, I sort the `__wcdb_ORMColumnCoding_synthesize_*` in `WCTBinding` to make sure the order.
Is that right?

**Comment by zhongwuzw** [comment]
@RingoD Nope, after you sorted. leads to misorder either. you can make a breakpoint when doing `binding .addColumnBinding` to see the property binding order.

**Comment by RingoD** [comment]
Yes, you are right.

I mean to sort it with numeric order. But it seems like not working as I expected.
Now it's fixed: https://github.com/Tencent/wcdb/commit/fb3d4a2f135ba8118bc37541b1ab038cd3dcad63

Actually, in most of case, the order is fine. But I do not find the standard of compiler to make a promise for this. Maybe it can be changed after some magical compiler optimization. So sorting is good.

Again, thanks for your PR and suggestion.

**Comment by zhongwuzw** [comment]
@RingoD 🍻🍻🍻.

 How about this #305? Just calculate what we want.

**Pull request merged**
