### PR TITLE
[Feature] Make function param `table` RawPresentable

### PR DESCRIPTION
**Pull request by CodeEagle**
## Motivation 
`String`s are evil. 

We can use `Enum` or any other `RawRepresentable` to represent `table` name

## UniTests
- [x] All Testcases passed

### CODE REVIEW

**Comment by RingoD** [comment]
Why do you think string is evil?

**Comment by CodeEagle** [comment]
```
let object = Sample()
sample.identifier = 1
sample.description = "insert"
try database.insert(objects: object, intoTable: "sampleTable") // 插入成功

try database.insert(objects: object, intoTable: "sampleTable") // 插入失败，因为主键 identifier = 1 已经存在

sample.description = "insertOrReplace"
try database.insertOrReplace(objects: object, intoTable: "sampleTable") // 插入成功，且 description 的内容会被替换为 "insertOrReplace"
```
As the example above, `"sampleTable"` is using everywhere without a compile time checking,  easier driving the wrong way.

Another solution is using a `static var` for class to hold the name, it's using in the test case.

IMO,  the most `Swift` way organizing the resources is using `enum` 🤓.

**Comment by RingoD** [comment]
Truly, using `enum` to organize the resources is a great way.
 
But I don't think WCDB should provide a built-in support.
As an example, `FileManager.removeItem` does not accept a `RawRepresentable` parameter. Instead, developers should give a `String` parameter named `path` for it. 
As for the `path` resources, developers can store them by `enum` and call it by `rawValue`.

Same as WCDB.

**Comment by CodeEagle** [comment]
Hi @RingoD 
> As for the path resources, developers can store them by `enum` and call it by `rawValue`.

Yes, but calling `rawValue` every is so noising and redundant.

> `FileManager.removeItem` does not accept a `RawRepresentable` parameter

As you mention above, we still can `extension FileManager` to support it.

As as third-party sdk, should provide a better choice for user, leading them to run the recommend way.

What system provide is a standard, but we still can provide a better solution. That's why so many open source software exist.😄

**Comment by RingoD** [comment]
Thanks for your suggestion. I think you are right.

But the code is not perfect enough. Here is some suggestions for improvement:
1. A `RawRepresentable` `String` will invaded the whole Swift project. Let code talks:
```
func test<T: RawRepresentable>(_ _: T) where T.RawValue == String {}
func test<T: StringProtocol>(_ _: T) {}
test("test") // Compiler Error: Ambiguous use of 'test'
```
There is nothing wrong before a `RawRepresentable` `String`. But now, it fails.
Maybe you should use your own protocol to accept both `RawRepresentable` and `String` parameters.

2. Please replace the header of `String+RawRepresentable` into the license declaration.

**Comment by CodeEagle** [comment]
Hi @RingoD 
ok, I'll improve it later.😁

**Comment by CodeEagle** [comment]
Hi @RingoD
How about this implementation.

**Comment by RingoD** [comment]
I don't think it's a good solution.
You added a bunch of code, and new code will need to added once I write a function with `String` parameter. The only thing improved is to reduce one `rawValue` call.
It's not worth.

**Comment by CodeEagle** [comment]
Yep. But still not found a good solution for the feature.
May be some how in future will have a elegant one😁.

**Comment by RingoD** [comment]
Not a good PR.

**Pull request closed without merging**
