### PR TITLE
Fix Notification name didReceiveMemorywarning for Swift 4.2

### PR DESCRIPTION
**Pull request by looseyi**

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/wcdb?pullRequest=385) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/wcdb?pullRequest=385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/wcdb?pullRequest=385) it.</sub>

**Comment by RingoD** [comment]
Is Swift 4.2 compatible for those project specified with Swift 4.0 (Both build in Xcode 10)?

**Comment by RingoD** [comment]
We will launch a new version to fit the Swift 4.2 sooner or later.

**Comment by looseyi** [comment]
can't wait to see that😁

**Pull request merged**
