### PR TITLE
optimize some processing code

### PR DESCRIPTION
**Pull request by zhongwuzw**
1. Query wether table exists by `sqlite_master`.
2. Fix `TRANSACTION_EVENT` typo.
3. Remove unnecessary code.

### CODE REVIEW

**Comment by RingoD** [comment]
What's the difference between `SELECT 1 FROM tableName` and `SELECT 1 FROM tableName WHERE type="table" AND tbl_name = "tableName"` ?

**Comment by zhongwuzw** [comment]
@RingoD , the results that wether or not table exists has no difference. But `SELECT 1 FROM tableName` would cast exception if not exist, so we hardly figure out wether table not exist or just meet some other exceptions, only we can figure out is to get the information from error.
If we use `SELECT 1 FROM sqlite_master WHERE type="table" AND tbl_name = "tableName"`, once query done successfully, we can get the information of existence, no exception cast, we get error only in internal sqlite error. That's what I think about.

**Comment by RingoD** [comment]
Selecting from `sqlite_master` is slow since it has no index B-Tree. A full-table-iteration, with string comparison will happen, which is O(n).
In the contrast, `SELECT 1 FROM tableName` only trigger the builtin schema hash table, which is O(1). And not string comparison.

As for nonexistent table error, you can figure it out by `SQLITE_ERROR`.

**Comment by zhongwuzw** [comment]
@RingoD , Yep, you stand at the point of performance, I just try to stand by a user, if user call this method to figure out the existence of table, mostly, he wants get three results, exist, non-exist, or error, maybe he doesn't know that would get error if table not exists who not look into the code, this is misleading, sometimes we can suffer some performance penalty if we acceptable, in order to give the more clear expression. 
I can revert this change if you think the older one is better. :grinning:

**Comment by RingoD** [comment]
Since `SQLITE_ERROR` is processed as an inner error, developers will get an error only if something bad happen. In other words, it will not failed for a nonexistent table.

**Comment by zhongwuzw** [comment]
Emm, sorry, I don't understand it. you mean the `Objective-C` layer?

**Comment by RingoD** [comment]
I am talking about the implementation.

In the `ObjC` layer, both of these two implementation will `return NO` for an existing table while a fatal error happen.

**Comment by zhongwuzw** [comment]
@RingoD , I know that `Objc` method just return bool, `SQLITE_ERROR` only occur when `table` not exists? We need to find the `no such table` key word from error description if not.

It's alright, I reverted the code to recover the older handler.

**Comment by RingoD** [comment]
When a fatal error happens, both of these two implementation will return `NO`. There is nothing changes but performance degradation for `sqlite_master` selecting.
On the other hand, developers have nothing to do while a fatal error occurs. 
I don't think it's a better solution.

**Comment by zhongwuzw** [comment]
@RingoD Emm, I know your opinion:relaxed:, but I don't know wether you know what I think, I try to describe it again: when I call this method , and result return `NO`, at the moment, I can't say that the table not exist, right? because maybe some error occur, maybe `SQLITE_ERROR`,`SQLITE_BUSY `...., so , I will most likely retry it later to check, it would leads to infinite loop. Am I right?

**Comment by RingoD** [comment]
Things are same for your implementation.

**Pull request merged**
